# Generated by Django 4.1 on 2022-08-23 18:25

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=250)),
                ('contenido', ckeditor.fields.RichTextField()),
                ('frase', ckeditor.fields.RichTextField()),
                ('resumen', models.CharField(max_length=250)),
                ('tema', models.CharField(max_length=250)),
                ('fecha_publicacion', models.DateField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes')),
                ('estado', models.BooleanField()),
                ('autor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publicaciones.autor')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
